<a href="https://colab.research.google.com/github/redcoding72/EDUBlib-Introduction-Sciences-des-donn-e-AI/blob/main/lab_Dimensionality_Reduction_PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Tables des matières<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Réduction-de-dimensions-et-Analyse-de-composantes-principales-(ACP)" data-toc-modified-id="Réduction-de-dimensions-et-Analyse-de-composantes-principales-(ACP)-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Réduction de dimensions et Analyse de composantes principales (ACP)</a></span><ul class="toc-item"><li><span><a href="#Chargement-du-Iris-Dataset-(i.e.-scikit-learn-iris)" data-toc-modified-id="Chargement-du-Iris-Dataset-(i.e.-scikit-learn-iris)-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Chargement du Iris Dataset (i.e. scikit-learn iris)</a></span></li></ul></li></ul></div>


# Réduction de dimensions et Analyse de composantes principales (ACP)

In [9]:
# Imports de base
import numpy as np
import matplotlib.pyplot as plt
import pylab as pl
import pandas as pd
#from bokeh.plotting import figure,show,output_notebook

#import pour la classification
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
 
# import pour PCA
from sklearn.decomposition import PCA


## Chargement du Iris Dataset (i.e. scikit-learn iris)  


In [10]:
#Import du dataset Iris
from sklearn.datasets import load_iris
iris = load_iris()

In [11]:
#Afficher le dataset
print (iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [12]:
#Features et target
X = iris.data
y = iris.target
noms_target = iris.target_names

In [13]:
# creer le modele et effectuer un fit du data
pca = PCA(n_components=2)
X_resultat = pca.fit(X).transform(X)

In [14]:
X_resultat

array([[-2.68412563,  0.31939725],
       [-2.71414169, -0.17700123],
       [-2.88899057, -0.14494943],
       [-2.74534286, -0.31829898],
       [-2.72871654,  0.32675451],
       [-2.28085963,  0.74133045],
       [-2.82053775, -0.08946138],
       [-2.62614497,  0.16338496],
       [-2.88638273, -0.57831175],
       [-2.6727558 , -0.11377425],
       [-2.50694709,  0.6450689 ],
       [-2.61275523,  0.01472994],
       [-2.78610927, -0.235112  ],
       [-3.22380374, -0.51139459],
       [-2.64475039,  1.17876464],
       [-2.38603903,  1.33806233],
       [-2.62352788,  0.81067951],
       [-2.64829671,  0.31184914],
       [-2.19982032,  0.87283904],
       [-2.5879864 ,  0.51356031],
       [-2.31025622,  0.39134594],
       [-2.54370523,  0.43299606],
       [-3.21593942,  0.13346807],
       [-2.30273318,  0.09870885],
       [-2.35575405, -0.03728186],
       [-2.50666891, -0.14601688],
       [-2.46882007,  0.13095149],
       [-2.56231991,  0.36771886],
       [-2.63953472,

# On cherche maintenant le pourcentage de variance pris en charge par les 2 composantes PCA. On utilise l'attribut `explained_variance_ratio_` :

In [ ]:
# Pourcentage de variance explained  :
print ("Composant 1: " + str(pca.explained_variance_ratio_[0]))
print ("Composant 2: " + str(pca.explained_variance_ratio_[1]))

Composant 1: 0.9246162071742684
Composant 2: 0.053015567850534955


* On voit que les 2 composantes prennent en charge presque la totalité de la variance.  On procède maintenant au tracé des point du dataset dans le système de coordonnées ou bases PCA.  Les labels utilisés sont ceux des targets:

In [20]:
echelle_couleur = {0:'red',1:'blue',2:'orange'}

couleurs = list()

for valeur in y:
    couleur = echelle_couleur[valeur]
    couleurs.append(couleur)


In [ ]:
#Plot comme scatter
p_fig = plt.figure()

x_values =  X_resultat[:,0]
y_values =  X_resultat[:,1]
p_fig.circle(x = x_values,y=y_values,size = 5,color=couleurs)

show(p_fig)

# On utilise maintenant une technique simple pour evaluer si le choix de n=2 est adéquat.On refait la même procédure mais avec toutes les composantes:

In [23]:
# créer le modele mais sans spécifier n_components:
pca = PCA()
X_resultat = pca.fit(X).transform(X)

In [24]:
#Afficher les variances expliqués

In [25]:
variance_explique = pca.explained_variance_ratio_
print (variance_explique)

[0.92461872 0.05306648 0.01710261 0.00521218]


In [26]:
#Afficher les composantes PCA
print (pca.components_)

[[ 0.36138659 -0.08452251  0.85667061  0.3582892 ]
 [ 0.65658877  0.73016143 -0.17337266 -0.07548102]
 [-0.58202985  0.59791083  0.07623608  0.54583143]
 [-0.31548719  0.3197231   0.47983899 -0.75365743]]


In [27]:
comp_id = [1, 2, 3, 4]             # id du composant
p_pca = figure(title="Composantes principales",tools='',
           x_axis_label="Principal Component",
          y_axis_label='Variance Expliquée')
p_pca.line(comp_id,variance_explique,color='red')
show(p_pca)


NameError: ignored

On voit qu’avec 2 composantes, on est capable de capturer l’essentiel des features.

# On evalue maintenant si la vitesse de traitement est améliorée en prenant moins de feature ou plus de features

In [28]:
modele = KNeighborsClassifier(2)
modele.fit(X_train, y_train)
print (classification_report(y_test,modele.predict(X_test)) )

NameError: ignored

In [29]:
X_r_train, X_r_test, y_r_train, y_r_test = train_test_split(X_resultat,y, test_size=0.2, random_state=42)

In [30]:
%%timeit 
modele = KNeighborsClassifier(2)
modele.fit(X_r_train, y_r_train)

The slowest run took 7.14 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 5: 308 µs per loop


In [31]:
modele = KNeighborsClassifier(2)
modele.fit(X_r_train, y_r_train)
print (classification_report(y_r_test,modele.predict(X_r_test)) )

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [32]:
# refaire maintenant avec 2 composantes principales
# creer le modele et effectuer un fit du data
pca_2 = PCA(n_components=2)
X_resultat_2 = pca.fit(X).transform(X)
X_r_train2, X_r_test2, y_r_train2, y_r_test2 = train_test_split(X_resultat_2,y, test_size=0.2, random_state=42)


In [33]:
%%timeit 
modele = KNeighborsClassifier(2)
modele.fit(X_r_train2, y_r_train2)

The slowest run took 6.39 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 5: 314 µs per loop


In [34]:
modele2 = KNeighborsClassifier(2)
modele2.fit(X_r_train2, y_r_train2)
print (classification_report(y_r_test2,modele2.predict(X_r_test2)) )

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

